# Generated by Django 4.2.2 on 2023-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_order_form_record_order_form_alter_record_status_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='order_form',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
