# Generated by Django 4.2.2 on 2023-07-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_order_form_udid_record_udid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_form',
            name='udid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
