# Generated by Django 4.2.2 on 2023-07-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_order_form_udid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_form',
            name='udid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
