# Generated by Django 4.2.2 on 2023-07-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_order_form_udid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_form',
            old_name='udid',
            new_name='udid_key',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='udid',
            new_name='udid_key',
        ),
    ]
