# Generated by Django 4.2.2 on 2023-07-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_udid_order_form_udid_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_form',
            old_name='udid_key',
            new_name='unique_kye',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='udid_key',
            new_name='unique_kye',
        ),
    ]
