# Generated by Django 4.2.2 on 2023-07-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_udid_key_order_form_unique_kye_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_form',
            old_name='unique_kye',
            new_name='unique_key',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='unique_kye',
            new_name='unique_key',
        ),
    ]
