# Generated by Django 4.2.2 on 2023-07-16 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_unique_kye_order_form_unique_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='unique_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
