# Generated by Django 4.2.2 on 2023-07-16 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_record_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='unique_key',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
